### ISSUE TITLE
Project cannot be built

### ISSUE THREAD

**Issue by leven2012** [ow2-proactive/workflow-catalog#11]
i  try to build for example
gradle clean build war,but 

/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/entity/Workflow.java:80: 错误: 需要')'
        revisions.forEach(this::addRevision);
                              ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/entity/Workflow.java:80: 错误: 非法的表达式开始
        revisions.forEach(this::addRevision);
                               ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/entity/Workflow.java:80: 错误: 需要';'
        revisions.forEach(this::addRevision);
                                           ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/dto/GenericInformation.java:53: 错误: 非法的表达式开始
                .map(entity -> new GenericInformation(entity.getKey(), entity.getValue()))
                             ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/dto/Variable.java:56: 错误: 非法的表达式开始
        return from.stream().map(entity -> new Variable(entity.getKey(), entity.getValue()))
                                         ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/service/WorkflowRevisionService.java:163: 错误: 非法的表达式开始
                .map(entry -> new GenericInformation(entry.getKey(), entry.getValue()))
                            ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/service/WorkflowRevisionService.java:169: 错误: 非法的表达式开始
                .map(entry -> new Variable(entry.getKey(), entry.getValue()))
                            ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/service/BucketService.java:73: 错误: 需要')'
                        .anyMatch("test"::equals);
                                        ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/service/BucketService.java:73: 错误: 非法的表达式开始
                        .anyMatch("test"::equals);
                                         ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/service/BucketService.java:73: 错误: 需要';'
                        .anyMatch("test"::equals);
                                                ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/service/BucketService.java:77: 错误: 非法的表达式开始
                    name -> bucketRepository.save(new Bucket(name))
                          ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:181: 错误: 非法的表达式开始
        return () -> new UnprocessableEntityException("XML does not validate against Schema. " + message);
                ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:181: 错误: 非法的表达式开始
        return () -> new UnprocessableEntityException("XML does not validate against Schema. " + message);
                   ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:193: 错误: 需要')'
                (attributeName, attributeValue) -> {
                              ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:193: 错误: 非法的表达式开始
                (attributeName, attributeValue) -> {
                                                 ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:193: 错误: 非法的表达式开始
                (attributeName, attributeValue) -> {
                                                   ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:200: 错误: 非法的类型开始
        );
        ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:202: 错误: 需要<标识符>
        jobHandled = true;
                  ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:205: 错误: 需要class, interface或enum
    private void handleVariableElement(ImmutableMap.Builder<String, String> variables) {
            ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:210: 错误: 需要class, interface或enum
    }
    ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:214: 错误: 需要class, interface或enum
        String[] value = new String[1];
        ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:216: 错误: 需要class, interface或enum
        iterateOverAttributes(
        ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:220: 错误: 需要class, interface或enum
                    } else if (attributeName.equals(attributeNameForValue)) {
                    ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:222: 错误: 需要class, interface或enum
                    }
                    ^
/home/leven/proactive/workflow-catalog-7.4.X/src/main/java/org/ow2/proactive/workflow_catalog/rest/util/ProActiveWorkflowParser.java:226: 错误: 需要class, interface或enum
        store.put(key[0], value[0]);
        ^

**Comment by paraita** [comment]
Hi,
I just tried to reproduce your error in vain. I checked out the 7.4.X branch (you seem to be using that version) and ran `gradle clean build war`. It all went fine without errors.
The Workflow Catalog also requires Java 8, do you have it installed ? Can you provide more information ?

Regards

**Comment by laurentpellegrino** [comment]
@leven2012 Have you tried to compile using JDK in version 8?

**Comment by leven2012** [comment]
sorry I compile using jdk in version 7,thank you!
